### ISSUE TITLE
Not sure why it's not working (Attached docker log)

### ISSUE THREAD

**Issue by ds1dbx** [jc1518/Akamai-Bot#1]
Hi Jackie.

I've setup docker and akamai-bot was properly added to my team successfully.
I added bot into specific channel to make interaction but noting returned back from bot.
Can you please look into below docker logs?

-----------------
[Fri Dec 02 2016 08:49:40 GMT+0000 (UTC)] INFO Logged in as akamai-bot of nopd-slack
[Fri Dec 02 2016 08:49:41 GMT+0000 (UTC)] INFO Slack client now connected
[Fri Dec 02 2016 08:49:41 GMT+0000 (UTC)] WARNING Expected /akamai-bot/scripts/akamaiApi to assign a function to module.exports, got object
[Fri Dec 02 2016 08:49:41 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

Your hubot-scripts.json is empty, so you just need to remove it.
[Fri Dec 02 2016 08:49:41 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
[Fri Dec 02 2016 08:49:41 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379

**Comment by jc1518** [comment]
HI @ds1dbx , you need to '@' the bot when you chat in Slack channel. e.g '@akamai-bot akamai help'. Or just send direct message to the bot.
